server {
  listen 80;
  server_name _;

  location = / {
    return 302 /operator/;
  }

  location = /operator {
    return 302 /operator/;
  }

  location = /login {
    return 302 /operator/login;
  }

  location /operator/ {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /operator/index.html;
  }

}
