# ===========================================================================
# AI Platform Engine - developer task runner.
# Run `make help` for the list of targets.
# On Windows, use Git Bash / WSL, or run the underlying commands directly.
# ===========================================================================
PY ?= python
PIP ?= $(PY) -m pip
COMPOSE ?= docker compose

.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'

# --- Environment ------------------------------------------------------------
.PHONY: venv
venv: ## Create a local virtual environment in .venv
	$(PY) -m venv .venv

.PHONY: install
install: ## Install development dependencies
	$(PIP) install -r requirements/dev.txt

.PHONY: env
env: ## Create .env from .env.example (if missing)
	@test -f .env || cp .env.example .env

# --- Run --------------------------------------------------------------------
.PHONY: run
run: ## Run the API locally with autoreload
	cd backend && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

# --- Quality ----------------------------------------------------------------
.PHONY: lint
lint: ## Lint with Ruff
	ruff check .

.PHONY: format
format: ## Auto-format with Ruff
	ruff format .
	ruff check . --fix

.PHONY: typecheck
typecheck: ## Static type checking with mypy
	mypy

.PHONY: test
test: ## Run the test suite
	pytest

.PHONY: cov
cov: ## Run tests with coverage report
	pytest --cov --cov-report=term-missing

.PHONY: check
check: lint typecheck test ## Run lint + types + tests

# --- Database / migrations --------------------------------------------------
.PHONY: migrate
migrate: ## Apply all migrations (alembic upgrade head)
	alembic upgrade head

.PHONY: migration
migration: ## Create a new autogenerated migration: make migration m="message"
	alembic revision --autogenerate -m "$(m)"

.PHONY: downgrade
downgrade: ## Roll back the last migration
	alembic downgrade -1

# --- Docker -----------------------------------------------------------------
.PHONY: up
up: ## Start the full stack (build + run, detached)
	$(COMPOSE) up --build -d

.PHONY: down
down: ## Stop the stack
	$(COMPOSE) down

.PHONY: down-volumes
down-volumes: ## Stop the stack and remove named volumes
	$(COMPOSE) down -v

.PHONY: logs
logs: ## Tail backend logs
	$(COMPOSE) logs -f backend

.PHONY: ps
ps: ## Show stack status
	$(COMPOSE) ps

# --- Hooks ------------------------------------------------------------------
.PHONY: hooks
hooks: ## Install pre-commit git hooks
	pre-commit install

.PHONY: precommit
precommit: ## Run all pre-commit hooks on all files
	pre-commit run --all-files
